### ISSUE TITLE
Backpack connect test suite is fragile

### ISSUE THREAD

**Issue by toolness** [mozilla/openbadges-backpack#831]
On my setup, running `test/backpack-connect.test.js`fails with the following:

```
not ok 12 POST http://localhost:54396/accept header "location" is http://localhost:54397/callback?access_token=1234&refresh_token=1234&expires=3600&api_root=http%3A%2F%2Flocalhost%3A54396%2Fapi
  ---
    file:   /Users/atul/Documents/mozilla/openbadges/test/app-utils.js
    line:   103
    column: 49
    stack:  
      - getCaller (/Users/atul/Documents/mozilla/openbadges/node_modules/tap/lib/tap-assert.js:418:17)
      - assert (/Users/atul/Documents/mozilla/openbadges/node_modules/tap/lib/tap-assert.js:21:16)
      - Function.equivalent (/Users/atul/Documents/mozilla/openbadges/node_modules/tap/lib/tap-assert.js:182:12)
      - Test._testAssert (/Users/atul/Documents/mozilla/openbadges/node_modules/tap/lib/tap-test.js:86:16)
      - /Users/atul/Documents/mozilla/openbadges/test/app-utils.js:113:15
      - Array.forEach (native)
      - Request._callback (/Users/atul/Documents/mozilla/openbadges/test/app-utils.js:103:49)
      - Request.init.self.callback (/Users/atul/Documents/mozilla/openbadges/node_modules/request/main.js:120:22)
      - Request.EventEmitter.emit (events.js:91:17)
      - Request.<anonymous> (/Users/atul/Documents/mozilla/openbadges/node_modules/request/main.js:555:16)
    found:  http://localhost:54397/callback?access_token=1234&refresh_token=1234&expires=3600&api_root=http%3A%2F%2F192.168.206.1%3A54396%2Fapi
    wanted: http://localhost:54397/callback?access_token=1234&refresh_token=1234&expires=3600&api_root=http%3A%2F%2Flocalhost%3A54396%2Fapi
    diff:   |
      FOUND:  i_root=http%3A%2F%2F192.168.206.1%3A5439
      WANTED: i_root=http%3A%2F%2Flocalhost%3A54396%2F
                                  ^ (at position = 104)
  ...
```

Alas.
